[project]
name = "v6-analytics"
version = "1.0.0"
description = "This will analyze the data extracted by the v6-sessions algorithm."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "vantage6-algorithm-tools==5.0.0b1",
    "pandas==2.3.3",
    "pyarrow",
    "parquet-tools",
    "rpy2",
    "numpy==1.26.4",
    "ohdsi-common",
    "ohdsi-database-connector",
    "ohdsi-sqlrender",
    "scipy",
    "statsmodels",
    "formulaic",
]

[tool.setuptools]
packages = ["v6-analytics"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
